package Projeto; 
        
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/*
 *
 * @author jpexi
 */
public class Atribuicoes extends javax.swing.JFrame {
    ModelAtribuicao model = new ModelAtribuicao();
    
    /**
     * Creates new form Atribuicao
     */
    public Atribuicoes() {
        initComponents();
        this.boxPro.removeAllItems();
        this.boxDis.removeAllItems();
        tbAtribuicao.setModel(model);   
        this.model.ler();
        /*
        *
        *
        *
        *
        */
        ArrayList<Funcionario> funcionarios = new ArrayList();
        String path = "C:\\Users\\jpexi\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoFinal\\in.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(path))) {
			
			String line = br.readLine();
			line = br.readLine();
			while (line != null) {
				
				String[] vect = line.split(",");
				String nome = vect[0];
                                String salario = vect[1];
                                String area = vect[2];
				String cpf = vect[3];
                                Funcionario f = new Funcionario( nome, salario, area,cpf);
                               funcionarios.add(f);
                               String conteudo = f.getNome()+" ,"+f.getArea()+", "+f.getCpf()+",";
				this.boxPro.addItem(conteudo);
                               line = br.readLine();
                               System.out.println("entrou");
			}	
			
			System.out.println("PRODUCTS:");
			for (Funcionario p : funcionarios) {
				System.out.println(p);
                                //this.boxPro.addItemListener(conteudo);
			}
		}
		catch (IOException e) {
			System.out.println("Error: " + e.getMessage());
		}
        /*
        *
        *
        *
        *
        *
        *
        *
        */
        ArrayList<Disciplina> disciplinas = new ArrayList();
        String caminho = "C:\\Users\\jpexi\\OneDrive\\Documentos\\NetBeansProjects\\ProjetoFinal\\Disciplinas.txt";
        try (BufferedReader br = new BufferedReader(new FileReader(caminho))) {
			
			String line = br.readLine();
			line = br.readLine();
			while (line != null) {
				
                            
                            
                                String[] vect = line.split(",");
				String nome = vect[0];
                                String area = vect[1];
				Double horas = Double.valueOf(vect[2]);
				String id = vect[3];
                                Disciplina h = new Disciplina( nome, area,  horas,  id);
                                disciplinas.add(h);
                               String conteudo = h.getNome()+" ,"+h.getArea()+", "+h.getId()+",";
				this.boxDis.addItem(conteudo);
                                line = br.readLine();
                                System.out.println("entrou");
                                
				/*String[] vect = line.split(",");
				String nome = vect[0];
                                String salario = vect[1];
                                String area = vect[2];
				String cpf = vect[3];
                                Funcionario f = new Funcionario( nome, salario, area,cpf);
                               funcionarios.add(f);
                               String conteudo = f.getNome()+" ("+f.getArea()+", "+f.getCpf()+")";
				this.boxPro.addItem(conteudo);
                               line = br.readLine();
                               System.out.println("entrou");*/
			}	
			
			System.out.println("PRODUCTS:");
			for (Disciplina p : disciplinas) {
				System.out.println(p);
                                //this.boxPro.addItemListener(conteudo);
			}
		}
		catch (IOException e) {
			System.out.println("Error: " + e.getMessage());
		}
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAtribuicao = new javax.swing.JTable();
        boxPro = new javax.swing.JComboBox<>();
        boxDis = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Atribuições");

        tbAtribuicao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAtribuicao.setPreferredSize(new java.awt.Dimension(400, 80));
        jScrollPane1.setViewportView(tbAtribuicao);

        boxPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxProActionPerformed(evt);
            }
        });

        boxDis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        boxDis.setPreferredSize(new java.awt.Dimension(250, 60));
        boxDis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boxDisMouseClicked(evt);
            }
        });
        boxDis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxDisActionPerformed(evt);
            }
        });

        jLabel2.setText("Professores");

        jLabel3.setText("Disciplinas");

        jButton2.setText("Atribuir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Excluir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Gravar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(143, 143, 143)
                                .addComponent(jLabel1))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(boxPro, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(boxDis, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxPro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxDis, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Pagina_Inicial altprd = new Pagina_Inicial();
        this.dispose();
        altprd.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boxProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxProActionPerformed
   
    }//GEN-LAST:event_boxProActionPerformed

    private void boxDisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxDisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxDisActionPerformed

    private void boxDisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boxDisMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_boxDisMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

         Atribuicao h = gerarAtribuicao();
         this.model.cadastrarDisciplina(h);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int index = tbAtribuicao.getSelectedRow();
        this.model.removerAtribuicao(index);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int somaLinhas = tbAtribuicao.getRowCount();
        this.model.gravard(somaLinhas);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    public Atribuicao gerarAtribuicao(){
        String itemPro = (String) boxPro.getSelectedItem();
        //String line =
        String[] vect = itemPro.split(",");
        String nome = vect[0];
        String aux = vect[1];
        String area = vect[2];
        
        
        String itemDis = (String) boxDis.getSelectedItem();
        String[] vect2 = itemDis.split(",");
        String horas = vect2[0];
        String aux2 = vect2[1];
        String id = vect2[2];
        Atribuicao h = new Atribuicao(nome, area,horas, id);
        return h;
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Atribuicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Atribuicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Atribuicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Atribuicoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Atribuicoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDis;
    private javax.swing.JComboBox<String> boxPro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbAtribuicao;
    // End of variables declaration//GEN-END:variables
}
